stages:
  ingest:
    cmd: /home/appuser/venv/bin/python src/ingest.py
    deps:
    - src/ingest.py
    params:
    - ingest.dcount
    outs:
    - data/prepared
  predict:
    cmd: /home/appuser/venv/bin/python src/predict.py data/prepared data/predictions data/store
    deps:
    - data/prepared
    - src/predict.py
    params:
    - ingest.dcount
    outs:
    - data/predictions